In [20]:
import pandas as pd
import numpy as np

In [21]:
df=pd.read_csv("dataset.csv")

In [22]:
df.head()

,Unnamed: 0,tesisat_no_id,il,ilce,gerilim_seviyesi,marka,model,abone_grubu,son_carpan_degeri,l1,l2,l3,v1,v2,v3,t0,ri,rc,load_profile_date
0,0,208e38ba076e428c9e5c9d9c0bd53f3f,ORDU,Gölköy,OG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane OG,1,0.0,64.67,0.01,233.75,222.62,232.08,415005.784,1019.784,2030.002,2025-08-01 00:00:00.000
1,1,208e38ba076e428c9e5c9d9c0bd53f3f,ORDU,Gölköy,OG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane OG,1,0.0,60.41,0.01,233.68,222.30,230.85,415009.205,1019.784,2030.013,2025-08-01 00:15:00.000
2,2,208e38ba076e428c9e5c9d9c0bd53f3f,ORDU,Gölköy,OG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane OG,1,0.0,63.23,0.01,233.48,222.11,230.98,415012.559,1019.784,2030.021,2025-08-01 00:30:00.000
3,3,208e38ba076e428c9e5c9d9c0bd53f3f,ORDU,Gölköy,OG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane OG,1,0.0,65.00,0.01,235.23,222.52,232.00,415015.917,1019.784,2030.033,2025-08-01 00:45:00.000
4,4,208e38ba076e428c9e5c9d9c0bd53f3f,ORDU,Gölköy,OG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane OG,1,0.0,62.46,0.01,234.70,222.52,231.78,415019.282,1019.784,2030.043,2025-08-01 01:00:00.000

In [23]:
df.tail()

,Unnamed: 0,tesisat_no_id,il,ilce,gerilim_seviyesi,marka,model,abone_grubu,son_carpan_degeri,l1,l2,l3,v1,v2,v3,t0,ri,rc,load_profile_date
353944,353944,3e63757c0d3a46f2b2ed1f2d489da6f6,ÇORUM,Bayat,AG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane AG,1,1.19,0.89,0.66,233.71,230.29,234.54,77887.259,4653.678,6773.270,2025-09-28 16:45:00.000
353945,353945,3e63757c0d3a46f2b2ed1f2d489da6f6,ÇORUM,Bayat,AG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane AG,1,1.33,0.80,0.58,234.73,232.59,234.11,77870.200,4652.817,6771.436,2025-09-28 03:15:00.000
353946,353946,3e63757c0d3a46f2b2ed1f2d489da6f6,ÇORUM,Bayat,AG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane AG,1,1.18,1.07,0.58,231.05,230.07,231.25,77866.923,4652.591,6771.048,2025-09-28 00:15:00.000
353947,353947,3e63757c0d3a46f2b2ed1f2d489da6f6,ÇORUM,Bayat,AG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane AG,1,1.50,0.94,0.35,229.49,228.29,231.80,77894.087,4654.089,6773.979,2025-09-28 22:15:00.000
353948,353948,3e63757c0d3a46f2b2ed1f2d489da6f6,ÇORUM,Bayat,AG,MAKEL,C500.KMY.2251,Tek Terimli Ticarethane AG,1,0.97,2.93,0.36,230.79,230.29,232.20,77895.804,4654.209,6774.161,2025-09-28 23:45:00.000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 353949 entries, 0 to 353948
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         353949 non-null  int64
 1   tesisat_no_id      353949 non-null  object
 2   il                 353949 non-null  object
 3   ilce               353949 non-null  object
 4   gerilim_seviyesi   353949 non-null  object
 5   marka              353949 non-null  object
 6   model              353949 non-null  object
 7   abone_grubu        353949 non-null  object
 8   son_carpan_degeri  353949 non-null  int64
 9   l1                 353949 non-null  float64
 10  l2                 353949 non-null  float64
 11  l3                 353949 non-null  float64
 12  v1                 278515 non-null  float64
 13  v2                 278515 non-null  float64
 14  v3                 278515 non-null  float64
 15  t0                 353949 non-null  float64
 16  ri                 343709 non-null  float64
 17  rc                 343709 non-null  float64
 18  load_profile_date  353949 non-null  object
dtypes: float64(9), int64(2), object(8)
memory usage: 51.3+ MB

In [25]:
df['load_profile_date'] = pd.to_datetime(df['load_profile_date'])

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 353949 entries, 0 to 353948
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         353949 non-null  int64
 1   tesisat_no_id      353949 non-null  object
 2   il                 353949 non-null  object
 3   ilce               353949 non-null  object
 4   gerilim_seviyesi   353949 non-null  object
 5   marka              353949 non-null  object
 6   model              353949 non-null  object
 7   abone_grubu        353949 non-null  object
 8   son_carpan_degeri  353949 non-null  int64
 9   l1                 353949 non-null  float64
 10  l2                 353949 non-null  float64
 11  l3                 353949 non-null  float64
 12  v1                 278515 non-null  float64
 13  v2                 278515 non-null  float64
 14  v3                 278515 non-null  float64
 15  t0                 353949 non-null  float64
 16  ri                 343709 non-null  float64
 17  rc                 343709 non-null  float64
 18  load_profile_date  353949 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int64(2), object(7)
memory usage: 51.3+ MB

In [27]:
print("Eksik Değer Sayıları:\n", df.isnull().sum())

Eksik Değer Sayıları:
 Unnamed: 0               0
tesisat_no_id            0
il                       0
ilce                     0
gerilim_seviyesi         0
marka                    0
model                    0
abone_grubu              0
son_carpan_degeri        0
l1                       0
l2                       0
l3                       0
v1                   75434
v2                   75434
v3                   75434
t0                       0
ri                   10240
rc                   10240
load_profile_date        0
dtype: int64

In [32]:
df = df.sort_values("load_profile_date")

df['v1'] = df['v1'].fillna(method="ffill")
df['v2'] = df['v2'].fillna(method="ffill")
df['v3'] = df['v3'].fillna(method="ffill")

C:\Users\pc\AppData\Local\Temp\ipykernel_17736\3742177971.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['v1'] = df['v1'].fillna(method="ffill")
C:\Users\pc\AppData\Local\Temp\ipykernel_17736\3742177971.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['v2'] = df['v2'].fillna(method="ffill")
C:\Users\pc\AppData\Local\Temp\ipykernel_17736\3742177971.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['v3'] = df['v3'].fillna(method="ffill")

In [33]:
print("Eksik Değer Sayıları:\n", df.isnull().sum())

Eksik Değer Sayıları:
 Unnamed: 0               0
tesisat_no_id            0
il                       0
ilce                     0
gerilim_seviyesi         0
marka                    0
model                    0
abone_grubu              0
son_carpan_degeri        0
l1                       0
l2                       0
l3                       0
v1                       0
v2                       0
v3                       0
t0                       0
ri                   10240
rc                   10240
load_profile_date        0
dtype: int64

In [36]:
df[["ri","rc"]].isnull().sum()
df[["ri","rc"]].isnull().mean()*100

ri    2.893072
rc    2.893072
dtype: float64

In [37]:
df = df.dropna(subset=["ri","rc"])

In [38]:
df.isnull().sum()

Unnamed: 0           0
tesisat_no_id        0
il                   0
ilce                 0
gerilim_seviyesi     0
marka                0
model                0
abone_grubu          0
son_carpan_degeri    0
l1                   0
l2                   0
l3                   0
v1                   0
v2                   0
v3                   0
t0                   0
ri                   0
rc                   0
load_profile_date    0
dtype: int64

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 343709 entries, 0 to 281977
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         343709 non-null  int64
 1   tesisat_no_id      343709 non-null  object
 2   il                 343709 non-null  object
 3   ilce               343709 non-null  object
 4   gerilim_seviyesi   343709 non-null  object
 5   marka              343709 non-null  object
 6   model              343709 non-null  object
 7   abone_grubu        343709 non-null  object
 8   son_carpan_degeri  343709 non-null  int64
 9   l1                 343709 non-null  float64
 10  l2                 343709 non-null  float64
 11  l3                 343709 non-null  float64
 12  v1                 343709 non-null  float64
 13  v2                 343709 non-null  float64
 14  v3                 343709 non-null  float64
 15  t0                 343709 non-null  float64
 16  ri                 343709 non-null  float64
 17  rc                 343709 non-null  float64
 18  load_profile_date  343709 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(9), int64(2), object(7)
memory usage: 52.4+ MB

In [41]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns
numeric_cols

Index(['Unnamed: 0', 'son_carpan_degeri', 'l1', 'l2', 'l3', 'v1', 'v2', 'v3',
       't0', 'ri', 'rc'],
      dtype='object')

In [42]:
(df[numeric_cols] < 0).sum()

Unnamed: 0           0
son_carpan_degeri    0
l1                   0
l2                   0
l3                   0
v1                   0
v2                   0
v3                   0
t0                   0
ri                   0
rc                   0
dtype: int64

In [53]:
Q1 = df["t0"].quantile(0.25)
Q3 = df["t0"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df["t0"] < lower) | (df["t0"] > upper)]

In [54]:
len(outliers)

59955

In [55]:
outlier_dict = {}

for col in numeric_cols:
    
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    
    outlier_dict[col] = len(outliers)

outlier_dict

{'Unnamed: 0': 0,
 'son_carpan_degeri': 29330,
 'l1': 45913,
 'l2': 43073,
 'l3': 28884,
 'v1': 76102,
 'v2': 62694,
 'v3': 54944,
 't0': 59955,
 'ri': 61666,
 'rc': 40766}

IQR yöntemi kullanılarak aykırı değerler tespit edilmiştir. 
Enerji tüketim verilerinde bazı aykırı değerler gerçek operasyonel durumları temsil edebileceğinden bu değerler tamamen silinmemiş, analiz sırasında ayrıca değerlendirilmiştir.

# Ortalama Akım:
-Akım yüksek ama tüketim düşük → kaçak kullanım
-Akım düşük ama tüketim yüksek → sayaç hatası

In [56]:
df["avg_current"] = (df["l1"] + df["l2"] + df["l3"]) / 3

# Ortalama Gerilim:
-Düşük voltaj → şebeke problemi

In [57]:
df["avg_voltage"] = (df["v1"] + df["v2"] + df["v3"]) / 3

# Faz Dengesizliği
Fazlar çok farklıysa + yüksek akım varsa
-ekipman arızası / yük dengesizliği

In [58]:
df["phase_imbalance"] = df[["l1","l2","l3"]].max(axis=1) - df[["l1","l2","l3"]].min(axis=1)

# Akım-Rüketim Tutarsızlığı
Dünkü tüketim ile bugünkü tüketim farkı ama bunu her abone için ayrı hesaplamak gerekir.
-Bir gün aşırı artış → kaçak kullanım
-Uzun süre sabit → sayaç hatası

In [59]:
df = df.sort_values(["tesisat_no_id","load_profile_date"])

df["consumption_diff"] = df.groupby("tesisat_no_id")["t0"].diff()

# Gerilim Sapma Oranı
Gerilimin ortalamadan ne kadar saptığını ölçer.
-Yüksek sapma → şebeke problemi

In [60]:
df["voltage_deviation"] = (
    df[["v1","v2","v3"]].max(axis=1) - df[["v1","v2","v3"]].min(axis=1)
) / df["avg_voltage"]

# Saat Dilimi (Gece / Gündüz / Mesai)
-Gece yüksek tüketim → kaçak kullanım

In [61]:
df["hour"] = df["load_profile_date"].dt.hour

In [62]:
def time_period(hour):
    if 0 <= hour < 6:
        return "night"
    elif 6 <= hour < 18:
        return "day"
    else:
        return "evening"

df["time_period"] = df["hour"].apply(time_period)

In [65]:
df.columns

Index(['Unnamed: 0', 'tesisat_no_id', 'il', 'ilce', 'gerilim_seviyesi',
       'marka', 'model', 'abone_grubu', 'son_carpan_degeri', 'l1', 'l2', 'l3',
       'v1', 'v2', 'v3', 't0', 'ri', 'rc', 'load_profile_date', 'avg_current',
       'avg_voltage', 'phase_imbalance', 'consumption_diff',
       'voltage_deviation', 'hour', 'time_period'],
      dtype='object')

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 343709 entries, 7263 to 210362
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         343709 non-null  int64
 1   tesisat_no_id      343709 non-null  object
 2   il                 343709 non-null  object
 3   ilce               343709 non-null  object
 4   gerilim_seviyesi   343709 non-null  object
 5   marka              343709 non-null  object
 6   model              343709 non-null  object
 7   abone_grubu        343709 non-null  object
 8   son_carpan_degeri  343709 non-null  int64
 9   l1                 343709 non-null  float64
 10  l2                 343709 non-null  float64
 11  l3                 343709 non-null  float64
 12  v1                 343709 non-null  float64
 13  v2                 343709 non-null  float64
 14  v3                 343709 non-null  float64
 15  t0                 343709 non-null  float64
 16  ri                 343709 non-null  float64
 17  rc                 343709 non-null  float64
 18  load_profile_date  343709 non-null  datetime64[ns]
 19  avg_current        343709 non-null  float64
 20  avg_voltage        343709 non-null  float64
 21  phase_imbalance    343709 non-null  float64
 22  consumption_diff   343642 non-null  float64
 23  voltage_deviation  343697 non-null  float64
 24  hour               343709 non-null  int32
 25  time_period        343709 non-null  object
dtypes: datetime64[ns](1), float64(14), int32(1), int64(2), object(8)
memory usage: 69.5+ MB

In [67]:
df.to_csv("cleaned_energy_data.csv", index=False)

In [70]:
new_df=pd.read_csv("cleaned_energy_data.csv")

In [71]:
new_df.head()

,Unnamed: 0,tesisat_no_id,il,ilce,gerilim_seviyesi,marka,model,abone_grubu,son_carpan_degeri,l1,...,ri,rc,load_profile_date,avg_current,avg_voltage,phase_imbalance,consumption_diff,voltage_deviation,hour,time_period
0,7263,0a6bce9bc9a945c0acbd8c048cb1e0a0,ÇORUM,İskilip,OG,MAKEL,C500.KMY.2556,Tek Terimli Sanayi OG,120,0.009,...,344.506,574.341,2025-08-01 00:00:00,0.006000,226.423333,0.006,NaN,0.006625,0,night
1,7264,0a6bce9bc9a945c0acbd8c048cb1e0a0,ÇORUM,İskilip,OG,MAKEL,C500.KMY.2556,Tek Terimli Sanayi OG,120,0.009,...,344.507,574.341,2025-08-01 00:15:00,0.006000,225.530000,0.006,0.000,0.004035,0,night
2,7265,0a6bce9bc9a945c0acbd8c048cb1e0a0,ÇORUM,İskilip,OG,MAKEL,C500.KMY.2556,Tek Terimli Sanayi OG,120,0.009,...,344.507,574.341,2025-08-01 00:30:00,0.006000,226.806667,0.006,0.001,0.002469,0,night
3,7266,0a6bce9bc9a945c0acbd8c048cb1e0a0,ÇORUM,İskilip,OG,MAKEL,C500.KMY.2556,Tek Terimli Sanayi OG,120,0.002,...,344.507,574.342,2025-08-01 00:45:00,0.003667,226.540000,0.004,0.000,0.004635,0,night
4,7267,0a6bce9bc9a945c0acbd8c048cb1e0a0,ÇORUM,İskilip,OG,MAKEL,C500.KMY.2556,Tek Terimli Sanayi OG,120,0.003,...,344.507,574.342,2025-08-01 01:00:00,0.004000,226.086667,0.003,0.001,0.007165,1,night

In [72]:
new_df.isnull().sum()

Unnamed: 0            0
tesisat_no_id         0
il                    0
ilce                  0
gerilim_seviyesi      0
marka                 0
model                 0
abone_grubu           0
son_carpan_degeri     0
l1                    0
l2                    0
l3                    0
v1                    0
v2                    0
v3                    0
t0                    0
ri                    0
rc                    0
load_profile_date     0
avg_current           0
avg_voltage           0
phase_imbalance       0
consumption_diff     67
voltage_deviation    12
hour                  0
time_period           0
dtype: int64

In [73]:
new_df["consumption_diff"] = new_df["consumption_diff"].fillna(0)

In [74]:
new_df["voltage_deviation"] = new_df["voltage_deviation"].fillna(0)

In [75]:
new_df.isnull().sum()

Unnamed: 0           0
tesisat_no_id        0
il                   0
ilce                 0
gerilim_seviyesi     0
marka                0
model                0
abone_grubu          0
son_carpan_degeri    0
l1                   0
l2                   0
l3                   0
v1                   0
v2                   0
v3                   0
t0                   0
ri                   0
rc                   0
load_profile_date    0
avg_current          0
avg_voltage          0
phase_imbalance      0
consumption_diff     0
voltage_deviation    0
hour                 0
time_period          0
dtype: int64

In [80]:
df.to_csv("cleaned_energy_data.csv", index=False)

In [82]:
last=pd.read_csv("cleaned_energy_data.csv")

In [83]:
last.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343709 entries, 0 to 343708
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         343709 non-null  int64
 1   tesisat_no_id      343709 non-null  object
 2   il                 343709 non-null  object
 3   ilce               343709 non-null  object
 4   gerilim_seviyesi   343709 non-null  object
 5   marka              343709 non-null  object
 6   model              343709 non-null  object
 7   abone_grubu        343709 non-null  object
 8   son_carpan_degeri  343709 non-null  int64
 9   l1                 343709 non-null  float64
 10  l2                 343709 non-null  float64
 11  l3                 343709 non-null  float64
 12  v1                 343709 non-null  float64
 13  v2                 343709 non-null  float64
 14  v3                 343709 non-null  float64
 15  t0                 343709 non-null  float64
 16  ri                 343709 non-null  float64
 17  rc                 343709 non-null  float64
 18  load_profile_date  343709 non-null  object
 19  avg_current        343709 non-null  float64
 20  avg_voltage        343709 non-null  float64
 21  phase_imbalance    343709 non-null  float64
 22  consumption_diff   343642 non-null  float64
 23  voltage_deviation  343697 non-null  float64
 24  hour               343709 non-null  int64
 25  time_period        343709 non-null  object
dtypes: float64(14), int64(3), object(9)
memory usage: 68.2+ MB